services:
    dugun.twig.video:
        class: AppBundle\Twig\TwigExtension
        arguments: ['@monolog.logger.benchmark']
        public: false
        tags:
            - { name: 'twig.extension' }
